config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:"homes#top"

  resources :users, only: [:show, :edit, :update]
  get 'quit' => 'users#quit'
  patch 'out' => 'users#out'
  resources :items, only: [:index, :show, :edit, :update, :destroy, :new, :create] do
  resources :comments, only: [:create, :destroy]
  resources :bookmarks, only: [:index, :create, :destroy]
  end

  namespace :admin do
  resources :users, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user
  
  validates :comment, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  attachment :image
  has_many :tags, dependent: :destroy

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  with_options presence: true do
    validates :genre_id
    validates :name
    validates :price
    validates :image
    validates :delivery_date
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  with_options presence: true do
   validates :company_name
   validates :company_name_kana
   validates :postal_code
   validates :address
   validates :phone_number
   validates :email, uniqueness: true
   validates :encrypted_password
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to admin_user_path(@user.id)
    else
     render :edit
    end
  end

private
  def user_params
    params.require(:user).permit(:company_name, :company_name_kana, :postal_code, :address, :phone_number, :is_deleted )
  end
  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :image, :delivery_date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:company_name, :company_name_kana, :postal_code, :address, :phone_number, :email, :encrypted_password])
  end

  def after_sign_in_path_for(resource)
    items_path
  end

  # if resource_name == :admin
  #   root_path
  # elsif resource_name == :user
  #   new_user_registration_path
  # end
  # end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # before_action :set_item

  def index
   @user = current_user
   @bookmarks = @user.bookmarks.page(params[:page]).per(10)
  end

  def create
    @item = Item.find(params[:item_id])
    @bookmark = current_user.bookmarks.new(item_id: @item.id)
    @bookmark.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @item = Item.find(params[:item_id])
    @bookmark = current_user.bookmarks.find_by(item_id: @item.id)
    @bookmark.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :image, :delivery_date)
  end
  # def set_item
  #   @item = Item.find(params[:item_id])
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @item = Item.find(params[:item_id])
    @comment = @item.comments.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      flash[:notice] = 'コメント完了しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = 'コメント失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @item = Item.find(params[:item_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to item_path(params[:item_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
   before_action :authenticate_user!


  def index
    @items = Item.all.page(params[:page]).per(10)
    @q =Item.ransack(params[:q])
    @items = @q.result(distinct: true).page(params[:page]).per(10) if params[:q] # 後置
  end

  def show
    @item = Item.find(params[:id])
    @user = User.find(@item.user_id)
    @comment = Comment.new
    @comments = @item.comments
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = '編集完了しました'
      redirect_to items_path
    else
      flash[:alert] = '編集失敗しました'
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  def new
    @item = Item.new
    @items = Item.all
    @genres = Genre.all
  end

  def create
    # binding.pry
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    @genres = Genre.all
    # binding.pry
    if @item.save

     tags = Vision.get_image_data(@item.image)#APIタグ作成
     tags.each do |tag|
       @item.tags.create(name: tag)
     end

      flash[:notice] = '投稿完了しました'
      redirect_to items_path
    else
      flash[:alert] = '投稿失敗しました'
      render :new
    end


  end


  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :image, :delivery_date)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @item = @user.items
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      flash[:notice] = '編集完了しました'
      redirect_to user_params
    else
      flash[:alert] = '編集失敗しました'
      render :edit
    end
  end

  def quit
  end

  def out
    current_user.destroy #paranoidでdestroyが上書きされる
    reset_session
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:company_name, :company_name_kana, :postal_code, :address, :phone_number, :is_deleted )
  end
  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :image, :delivery_date)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmark.html.erb
<% if item.bookmarked_by?(current_user) %>
  <p>
  <%= link_to item_bookmark_path(item.id), method: :delete, remote: true do %>
  ★<%= item.bookmarks.count %>
  <% end %>
  </p>
  <% else %>
  <p>
  <%= link_to item_bookmarks_path(item.id), method: :post, remote: true do %>
  ☆<%= item.bookmarks.count %>
  <% end %>
  </p>
<% end %>

app/views/bookmarks/create.js.erb
$('#bookmarks_buttons_<%= @item.id %>').html("<%= j(render partial: 'bookmarks/bookmark', locals: {item: @item}) %>");

app/views/bookmarks/destroy.js.erb
$('#bookmarks_buttons_<%= @item.id %>').html("<%= j(render partial: 'bookmarks/bookmark', locals: {item: @item}) %>");

app/views/bookmarks/index.html.erb
<div class="container">
<div class="row">

<% @bookmarks.each do |bookmark| %>
<div class="box3">
  <div>
  <%= link_to item_path(bookmark.item.id) do %>
  <%= attachment_image_tag(bookmark.item, :image, size: "360x300", fallback: "no_image.jpg") %>
  <% end %>
  </div>
  <div>製品名：<%= bookmark.item.name %></div>
  <div>ジャンル名：<%= bookmark.item.genre.name %></div>
  <div>価格：<%= bookmark.item.price %>円</div>
  <div>納期:<%= bookmark.item.delivery_date %></div>
</div>
<% end %>

</div>
<%= paginate (@bookmarks) %>
</div>

app/views/comments/_comment.html.erb
<!--<div class="raw">-->
<h2>コメント</h2>
 <div class="comments">
  <% comments.each do |comment| %>
  <div class="row">
  <div class="col-12"><%= comment.user.company_name %></div>
  <div class="col-5"><%= comment.comment %></div>
  <div class="col-3"><%= link_to "削除", item_comment_path(item, comment), method: :delete, remote: true %></div>
  </div>
  <% end %>
 </div>

 <div class="row">
 <div><%=flash[:notice] %></div>
 <div><%=flash[:alert] %></div>
 <div>
   <%= form_with(model:[item, comment], remote: true) do |f| %>
    <%= f.text_area :comment %>
    <%= f.submit "送信する" %>
   <% end %>
 </div>
<!--</div>-->

app/views/comments/create.js.erb
$('#comments_buttons_<%= @item.id %>').html("<%= j(render partial: 'comments/comment', locals: {item: @item,comments: @comments,comment: @comment}) %>");

app/views/comments/destroy.js.erb
$('#comments_buttons_<%= @item.id %>').html("<%= j(render partial: 'comments/comment', locals: {item: @item,comments: @comments,comment: @comment}) %>");

app/views/items/edit.html.erb
<div class="container">
<div><%=flash[:alert] %></div>
<h1>投稿編集</h1>
<div class="row">


<%= form_with model:@item,url:item_path, method: :patch, local: true do |f| %>
<div>
  <p>図面</p>
  <%= f.attachment_field :image %>
</div>

<div>
  <p>製品名</p>
  <%= f.text_field :name %>
</div>

<div>
  <p>ジャンル名</p>
  <%= f.collection_select :genre_id, @genres, :id , :name  %>
</div>

<div>
  <p>価格</p>
  <%= f.text_field :price %>円
</div>

<div>
  <p>納期</p>
  <%= f.date_field :delivery_date %>
</div>

 <div>
  <p><%= f.submit '変更を保存', class: "btn btn-success" %></p>
</div>

<% end %>

</div>
</div>

app/views/items/index.html.erb
<div class="container">
  <div><%= search_form_for @q do |f| %>
        <%= f.label :name, "製品名検索" %>
        <%= f.search_field :name_cont %>
        <%= f.submit"検索" %>
       <% end %>
  </div>
  <div><%=flash[:notice] %></div>

  <div class="row">
  <% @items.each do |item| %>
    <div>
    <%= link_to item_path(item.id) do %>
    <%= attachment_image_tag(item, :image, size: "350x280", fallback: "no_image.jpg") %>
    <% end %>
    </div>
    <div class="col-6">
      <table border="1">
       <thead>
         <tr>
          <th>製品名</th>
          <th>ジャンル</th>
          <th>価格</th>
          <th>納期</th>
          <th></th>
          <th></th>
         </tr>
       </thead>
       <tbody>
         <tr>
          <td><%= item.name %></td>
          <td><%= item.genre.name %></td>
          <td><%= item.price %>円</td>
          <td><%= item.delivery_date %></td>
          <td><% if item.user == current_user %>
              <%= link_to "編集", edit_item_path(item) %>
              <% end %>
          </td>
          <td><% if item.user == current_user %>
              <%= link_to "削除", item_path(item), method: :delete %>
              <% end %>
          </td>
         </tr>
       </tbody>
       <div>
        <% item.tags.each do |tag| %>
         <span class="label"><%= tag.name %></span>
        <% end %>
       </div>
      </table>
    </div>
   <%= paginate (@items) %>
  <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="container">
<div><%=flash[:alert] %></div>
<h1>新規投稿</h1>
<div class="row">
<%= form_with model:@item, url:items_path, local:true, method: :post do |f| %>
    <div>
      <p>図面</p>
      <%= f.attachment_field :image %>
    </div>

    <div>
      <p>製品名</p>
      <%= f.text_field :name %>
    </div>

    <div>
      <p>価格</p>
      <%= f.text_field :price %>
    </div>

    <div>
      <p>ジャンル</p>
      <%= f.collection_select :genre_id, @genres, :id, :name %>
    </div>

    <div>
      <p>納期</p>
      <%= f.date_field :delivery_date %>
    </div>

  <%= f.submit '新規投稿', class: "btn btn-success" %>

 <% end %>
 </
 </div>

app/views/items/show.html.erb
<div class="container">
<div class="raw">
<div class="col-12">
 <div class="row">
 <div class="col-8 name-drawing">
  <div class="name">
     <%= link_to user_path(@user) do %>
     <%= @user.company_name %>
     <% end %>
  </div>
  <div class="n-drawing">
     <%= attachment_image_tag(@item, :image, size: "700x500", fallback: "no_image.jpg") %>
  </div>
 </div>

 <div class="col-2 detail">
  <div class="item-name">製品名：<%= @item.name %></div>
  <div class="item-genre">ジャンル：<%= @item.genre.name %></div>
  <div class="item-price">価格：<%= @item.price %>円</div>
  <div class="item-delivery">納期：<%= @item.delivery_date %></div>
  <div id="bookmarks_buttons_<%= @item.id %>"><%= render 'bookmarks/bookmark',item:@item %></div>
 </div>
 
 </div>
</div>
</div>

<div class="row">
 <div class="col-4">
 <div id="comments_buttons_<%= @item.id %>"><%= render 'comments/comment',item:@item,comments:@comments,comment:@comment %></div>
 </div>
</div>

</div>