config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:"homes#top"

  resources :users, only: [:show, :edit, :update]
  get 'quit' => 'users#quit'
  patch 'out' => 'users#out'
  resources :items, only: [:index, :show, :edit, :update, :destroy, :new, :create] do
  resources :comments, only: [:create, :destroy]
  resources :bookmarks, only: [:index, :create, :destroy]
  end

  namespace :admin do
  resources :users, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 before_action :authenticate_admin!

  def index
    @genres = Genre.all.page(params[:page]).per(10)
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
    redirect_to admin_genres_path
    else
    @genres = Genre.all.page(params[:page]).per(10)
    render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :created_at, :updated_at)
  end

end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController

  def index
    @genres = Genre.all.page(params[:page]).per(10)
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
    redirect_to admins_genres_path
    else
    @genres = Genre.all.page(params[:page]).per(10)
    render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admins_genres_path
    else
      render :edit
    end
  end
  
  private
  def genre_params
    params.require(:genre).permit(:name, :created_at, :updated_at)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admins/genres/edit.html.erb
<div class="container">

<div>
<%= form_with model:@genre,url: admins_genre_path(@genre), method: :patch, local:true do |f| %>
      <div>ジャンル名</div>
      <div><%= f.text_field :name %></div>
      <div><%= f.submit '変更を保存', class: "btn btn-success"  %></div>
<% end %>
</div>

</div>

app/views/admins/genres/index.html.erb
<div class="container">
<h1>ジャンル作成</h1>

<div class="row">
  <%= form_with model:@genre, url:admins_genres_path, method: :post, local:true do |f| %>
    <div class="form-group">
      <div>ジャンル名</div>
      <div><%= f.text_field :name %></div>
      <div><%= f.submit '新規登録', class: "btn btn-success" %></div>
    </div>
  <% end %>
</div>


<div class="row">
 <table border="genres">
 <% @genres.each do |genre| %>
 <thead>
  <tr>
    <th>
      <%= genre.name %>
      <%= link_to "編集する",  edit_admins_genre_path(genre), class: "btn btn-success" %>
    </th>
  </tr>
 </thed>
 <% end %>
 </table>
</div>
  <%= paginate(@genres) %>

</div>