config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:"homes#top"

  resources :users, only: [:show, :edit, :update]
  get 'quit' => 'users#quit'
  patch 'out' => 'users#out'
  resources :items, only: [:index, :show, :edit, :update, :destroy, :new, :create] do
  resources :comments, only: [:create, :destroy]
  resources :bookmarks, only: [:index, :create, :destroy]
  end

  namespace :admin do
  resources :users, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  with_options presence: true do
   validates :company_name
   validates :company_name_kana
   validates :postal_code
   validates :address
   validates :phone_number
   validates :email, uniqueness: true
   validates :encrypted_password
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to admin_user_path(@user.id)
    else
     render :edit
    end
  end

private
  def user_params
    params.require(:user).permit(:company_name, :company_name_kana, :postal_code, :address, :phone_number, :is_deleted )
  end
  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :image, :delivery_date)
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to admins_user_path(@user.id)
    else
     render :edit
    end
  end
  
private
  def user_params
    params.require(:user).permit(:company_name, :company_name_kana, :postal_code, :address, :phone_number, :is_deleted )
  end  
  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :image, :delivery_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @item = @user.items
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      flash[:notice] = '編集完了しました'
      redirect_to user_params
    else
      flash[:alert] = '編集失敗しました'
      render :edit
    end
  end

  def quit
  end

  def out
    current_user.destroy #paranoidでdestroyが上書きされる
    reset_session
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:company_name, :company_name_kana, :postal_code, :address, :phone_number, :is_deleted )
  end
  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :image, :delivery_date)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
<div><%=flash[:alert] %></div>
<h1>会員情報編集</h1>

<div class="mx-auto">
<div class="text-center edit-box">
<%= form_with model:current_user,　url:user_path, local: true do |f| %>
  <div>会社名</div>
  <%= f.text_field :company_name %>

  <div>カナ</div>
  <%= f.text_field :company_name_kana %>

  <div>郵便番号</div>
  <%= f.text_field :postal_code %>

  <div>住所</div>
  <%= f.text_field :address %>

  <div>電話番号</div>
  <%= f.text_field :phone_number %>

<div>
  <%= f.submit "編集内容を保存" %>
</div>
<div>
  <%= link_to "退会する", quit_path %>
</div>
<% end %>

</div>
</div>
</div>

app/views/users/quit.html.erb
<div class="container">
<h1>本当に退会しますか？</h1>
<div class="row">
 <div>
  <%= link_to "退会しない", root_path %>/
 </div>
 <div>
  <%= link_to "退会する", out_path, method: :patch %>
 </div>

</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div><%=flash[:notice] %></div>
    <div class="row">
    <% if @user == current_user %>
    <h1>マイページ</h1>
    <% else %>
    <h1>ユーザー詳細</h1>
    <% end %>
    </div>

    <div class="row">
    <table border="2">
     <tbody>
      <tr>
        <th>会社名</th>
        <th><%= @user.company_name %></th>
      </tr>
      <tr>
        <th>カナ</th>
        <th><%= @user.company_name_kana %></th>
      </tr>
      <tr>
        <th>郵便番号</th>
        <th><%= @user.postal_code %></th>
      </tr>
      <tr>
        <th>住所</th>
        <th><%= @user.address %></th>
      </tr>
     </tbody>
    </table>
    </div>

    <div class="row">
    <table>
     <tbody>
      <tr>
      　<th class="text-left">
      　     <% if @user == current_user %>
      　     <%= link_to "編集", edit_user_path(@user), class: "btn btn-success px-4" %>
      　     <% end %>
      　</th>
      　<th class="text-right">
      　  <font size="4">
         <% if @user == current_user %>
         <%= link_to "ブックマーク一覧", item_bookmarks_path(@item), class: "btn btn-success px-4" %>
         <% end %>
         </font>
        </th>
      </tr>
     </tbody>
    </table>
    </div>
</div>


<div class="container">
<h2>投稿一覧</h2>
<div class="row">
    <% @item.each do |item| %>
    <div class="drawing-box">
       <div class="drawing">
        <div class="drawing-image">
            <%= link_to item_path(item.id) do %>
            <%= attachment_image_tag(item, :image, size: "360x300", fallback: "no_image.jpg") %>
            <% end %>
        </div>
        <div><%= item.name %></div>
        <div><%= item.genre.name %></div>
        <div><%= item.price %>円</div>
        <div><%= item.delivery_date %></div>

        <div><% if item.user == current_user %>
             <%= link_to "編集", edit_item_path(item) %>/
             <% end %>

             <% if item.user == current_user %>
             <%= link_to "削除", item_path(item), method: :delete %>
             <% end %>
        </div>
       </div>
    </div>
    <% end %>
</div>
</div>