config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:"homes#top"

  resources :users, only: [:show, :edit, :update]
  get 'quit' => 'users#quit'
  patch 'out' => 'users#out'
  resources :items, only: [:index, :show, :edit, :update, :destroy, :new, :create] do
  resources :comments, only: [:create, :destroy]
  resources :bookmarks, only: [:index, :create, :destroy]
  end

  namespace :admin do
  resources :users, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user
  
  validates :comment, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  attachment :image
  has_many :tags, dependent: :destroy

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  with_options presence: true do
    validates :genre_id
    validates :name
    validates :price
    validates :image
    validates :delivery_date
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  with_options presence: true do
   validates :company_name
   validates :company_name_kana
   validates :postal_code
   validates :address
   validates :phone_number
   validates :email, uniqueness: true
   validates :encrypted_password
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:company_name, :company_name_kana, :postal_code, :address, :phone_number, :email, :encrypted_password])
  end

  def after_sign_in_path_for(resource)
    items_path
  end

  # if resource_name == :admin
  #   root_path
  # elsif resource_name == :user
  #   new_user_registration_path
  # end
  # end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # before_action :set_item

  def index
   @user = current_user
   @bookmarks = @user.bookmarks.page(params[:page]).per(10)
  end

  def create
    @item = Item.find(params[:item_id])
    @bookmark = current_user.bookmarks.new(item_id: @item.id)
    @bookmark.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @item = Item.find(params[:item_id])
    @bookmark = current_user.bookmarks.find_by(item_id: @item.id)
    @bookmark.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :image, :delivery_date)
  end
  # def set_item
  #   @item = Item.find(params[:item_id])
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @item = Item.find(params[:item_id])
    @comment = @item.comments.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      flash[:notice] = 'コメント完了しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = 'コメント失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @item = Item.find(params[:item_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to item_path(params[:item_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
   before_action :authenticate_user!


  def index
    @items = Item.all.page(params[:page]).per(10)
    @q =Item.ransack(params[:q])
    @items = @q.result(distinct: true).page(params[:page]).per(10) if params[:q] # 後置
  end

  def show
    @item = Item.find(params[:id])
    @user = User.find(@item.user_id)
    @comment = Comment.new
    @comments = @item.comments
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = '編集完了しました'
      redirect_to items_path
    else
      flash[:alert] = '編集失敗しました'
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  def new
    @item = Item.new
    @items = Item.all
    @genres = Genre.all
  end

  def create
    # binding.pry
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    @genres = Genre.all
    # binding.pry
    if @item.save

     tags = Vision.get_image_data(@item.image)#APIタグ作成
     tags.each do |tag|
       @item.tags.create(name: tag)
     end

      flash[:notice] = '投稿完了しました'
      redirect_to items_path
    else
      flash[:alert] = '投稿失敗しました'
      render :new
    end


  end


  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :image, :delivery_date)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @item = @user.items
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      flash[:notice] = '編集完了しました'
      redirect_to user_params
    else
      flash[:alert] = '編集失敗しました'
      render :edit
    end
  end

  def quit
  end

  def out
    current_user.destroy #paranoidでdestroyが上書きされる
    reset_session
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:company_name, :company_name_kana, :postal_code, :address, :phone_number, :is_deleted )
  end
  def item_params
    params.require(:item).permit(:genre_id, :name, :price, :image, :delivery_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ironworks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body>
    <header class="bg-dark text-white">
      <!--<nav class="navbar navbar-expand-lg navbar-dark bg-dark">-->
        <div class="container">
           <div class="col-12 text-center">
           <%= link_to "Ironworks", root_path, class: 'navbar-brand text-white' %>
           </div>
        </div>
        <div class="container">
            <ul class="navbar ml-auto header-space">
            <% if user_signed_in? %>
              <li class="nav-item"><%= link_to "マイページ", user_path(current_user.id), class: 'nav-link text-white' %></li>
              <li class="nav-item"><%= link_to "図面一覧", items_path, class: 'nav-link text-white' %></li>
              <li class="nav-item"><%= link_to "投稿", new_item_path, class: 'nav-link text-white' %></li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-white' %></li>

            <% elsif admin_signed_in? %>
          　  <li class"nav-item"><%= link_to "会員一覧", admin_users_path %></li>
             <li class="nav-item"><%= link_to "ジャンル一覧", admin_genres_path %></li>
             <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>

            <% else %>
              <li class="nav-item"><%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-white' %></li>
              <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: 'nav-link text-white' %></li>
            <% end %>
            </ul>
          </div>
      <!--</nav>-->
    </header>
    <%= yield %>
  </body>
</html>